spring:
  application:
    name: Manager
  datasource:
    url: jdbc:mysql://localhost:3306/db_manager?useSSL=false
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: validate
      
  flyway:
    url: jdbc:mysql://localhost:3306/db_manager?useSSL=false
    user: root
    password: root
    schemas:
    - db_manager
server:
  port: 8080
logging:
  level:
    org.flywaydb: DEBUG